(define (equal? sent1 sent2)
        (cond ((and (null? sent1)
                    (null? sent2))
               #t)
              ((not (eq? (car sent1)
                       (car sent2)))
               #f)
              (else (equal? (cdr sent1)
                      (cdr sent2)))))
